//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG.Infraestructura.AccesoDatos
{
    using SG.Dominio.Modelo.Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class depositoEntities : DbContext
    {
        public depositoEntities()
            : base("name=depositoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<credit> credit { get; set; }
        public virtual DbSet<credits_details> credits_details { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<stock_adjusts> stock_adjusts { get; set; }
        public virtual DbSet<stock_moves> stock_moves { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<transfer_types> transfer_types { get; set; }
        public virtual DbSet<transfers> transfers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
