//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class credits_details
    {
        public int credit_detail_id { get; set; }
        public Nullable<int> credit_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> week_id { get; set; }
        public string credit_detail_description { get; set; }
        public decimal credit_detail_value { get; set; }
    
        public virtual credit credit { get; set; }
        public virtual products products { get; set; }
    }
}
