//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.credits_details = new HashSet<credits_details>();
            this.stock_adjusts = new HashSet<stock_adjusts>();
            this.stock_moves = new HashSet<stock_moves>();
        }
    
        public int product_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string product_name { get; set; }
        public decimal product_sale_price { get; set; }
        public decimal product_purchase_price { get; set; }
        public string product_img { get; set; }
        public Nullable<int> product_stock_quantity { get; set; }
        public bool product_state { get; set; }
    
        public virtual categories categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<credits_details> credits_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_adjusts> stock_adjusts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_moves> stock_moves { get; set; }
    }
}
