//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_moves
    {
        public int stock_move_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> transfer_id { get; set; }
        public Nullable<int> stock_move_quantity { get; set; }
        public decimal stock_move_price_unit { get; set; }
    
        public virtual products products { get; set; }
        public virtual transfers transfers { get; set; }
    }
}
