//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_adjusts
    {
        public int stock_adjust_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public System.DateTime stock_adjust_date { get; set; }
        public Nullable<int> stock_adjust_quantity { get; set; }
        public string stock_adjust_reason { get; set; }
    
        public virtual products products { get; set; }
    }
}
