//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transfers()
        {
            this.stock_moves = new HashSet<stock_moves>();
        }
    
        public int transfer_id { get; set; }
        public Nullable<int> transfer_type_id { get; set; }
        public string transfer_number { get; set; }
        public System.DateTime transfer_date { get; set; }
        public System.DateTime transfer_created { get; set; }
        public string transfer_invoice_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_moves> stock_moves { get; set; }
        public virtual transfer_types transfer_types { get; set; }
    }
}
