//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer_types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transfer_types()
        {
            this.transfers = new HashSet<transfers>();
        }
    
        public int transfer_type_id { get; set; }
        public string TRANSFER_TYPE_NAME { get; set; }
        public string TRANSFER_TYPE_DESCRIPTION { get; set; }
        public bool TRANSFER_TYPE_STATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transfers> transfers { get; set; }
    }
}
